In [1]:
from google.colab import files
uploaded = files.upload()

Saving ColabFilterLearn.PNG to ColabFilterLearn.PNG
Saving ColabFilterUse.PNG to ColabFilterUse.PNG
Saving distmatrix.PNG to distmatrix.PNG
Saving film_award.png to film_award.png
Saving film_filter.png to film_filter.png
Saving film_man_action.png to film_man_action.png
Saving film_movie_camera.png to film_movie_camera.png
Saving film_rating.png to film_rating.png
Saving film_reel.png to film_reel.png
Saving film_strip_vertical.png to film_strip_vertical.png
Saving movie_camera.png to movie_camera.png
Saving public_tests.py to public_tests.py
Saving recsys_utils.py to recsys_utils.py
Saving RecSysNN.png to RecSysNN.png
Saving small_movie_list.csv to small_movie_list.csv
Saving small_movies_b.csv to small_movies_b.csv
Saving small_movies_R.csv to small_movies_R.csv
Saving small_movies_W.csv to small_movies_W.csv
Saving small_movies_X.csv to small_movies_X.csv
Saving small_movies_Y.csv to small_movies_Y.csv


In [2]:
!pip install ipympl

ERROR: Operation cancelled by user


In [53]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from recsys_utils import *

In [55]:
import os

# Mostrar el directorio actual
print("Directorio actual:", os.getcwd())

Directorio actual: /content


In [56]:
import os

# Verificar el contenido de la carpeta 'data'
print("Contenido de la carpeta 'data':")
print(os.listdir('./data'))

Contenido de la carpeta 'data':
[]


In [57]:
import numpy as np

def load_precalc_params_small():
    # Cambiar 'rb' a 'r' ya que estamos leyendo archivos CSV como texto
    file = open('./data/small_movies_X.csv', 'r')
    X = np.loadtxt(file, delimiter=",")
    file.close()

    file = open('./data/small_movies_W.csv', 'r')
    W = np.loadtxt(file, delimiter=",")
    file.close()

    file = open('./data/small_movies_b.csv', 'r')
    b = np.loadtxt(file, delimiter=",")
    file.close()

    num_movies, num_features = X.shape
    num_users = W.shape[1]

    return X, W, b, num_movies, num_features, num_users

def load_ratings_small():
    file = open('./data/small_movies_Y.csv', 'r')
    Y = np.loadtxt(file, delimiter=",")
    file.close()

    file = open('./data/small_movies_R.csv', 'r')
    R = np.loadtxt(file, delimiter=",")
    file.close()

    return Y, R

In [58]:
from google.colab import files

# Subir archivos desde tu máquina local
uploaded = files.upload()

# Mover los archivos subidos a la carpeta 'data'
for filename in uploaded.keys():
    !mv {filename} ./data/

Saving ColabFilterLearn.PNG to ColabFilterLearn (3).PNG
Saving ColabFilterUse.PNG to ColabFilterUse (3).PNG
Saving distmatrix.PNG to distmatrix (3).PNG
Saving film_award.png to film_award (3).png
Saving film_filter.png to film_filter (3).png
Saving film_man_action.png to film_man_action (3).png
Saving film_movie_camera.png to film_movie_camera (3).png
Saving film_rating.png to film_rating (3).png
Saving film_reel.png to film_reel (3).png
Saving film_strip_vertical.png to film_strip_vertical (3).png
Saving movie_camera.png to movie_camera (3).png
Saving public_tests.py to public_tests (3).py
Saving recsys_utils.py to recsys_utils (3).py
Saving RecSysNN.png to RecSysNN (3).png
Saving small_movie_list.csv to small_movie_list (4).csv
Saving small_movies_b.csv to small_movies_b (4).csv
Saving small_movies_R.csv to small_movies_R (4).csv
Saving small_movies_W.csv to small_movies_W (4).csv
Saving small_movies_X.csv to small_movies_X (4).csv
Saving small_movies_Y.csv to small_movies_Y (4).csv


In [59]:
import os

# Verificar la existencia de los archivos
print("Contenido de la carpeta 'data':")
print(os.listdir('./data'))

Contenido de la carpeta 'data':
[]


In [60]:
import os

# Crear la carpeta 'data' si no existe
if not os.path.exists('./data'):
    os.makedirs('./data')

# Verificar el contenido de la carpeta 'data'
print("Contenido de la carpeta 'data':")
print(os.listdir('./data'))

Contenido de la carpeta 'data':
[]


In [61]:
from google.colab import files

# Subir archivos desde tu máquina local
uploaded = files.upload()

# Mover los archivos subidos a la carpeta 'data'
for filename in uploaded.keys():
    destination = os.path.join('./data', filename)
    with open(destination, 'wb') as f:
        f.write(uploaded[filename])

# Verificar el contenido de la carpeta 'data'
print("Contenido de la carpeta 'data':")
print(os.listdir('./data'))

Saving ColabFilterLearn.PNG to ColabFilterLearn (4).PNG
Saving ColabFilterUse.PNG to ColabFilterUse (4).PNG
Saving distmatrix.PNG to distmatrix (4).PNG
Saving film_award.png to film_award (4).png
Saving film_filter.png to film_filter (4).png
Saving film_man_action.png to film_man_action (4).png
Saving film_movie_camera.png to film_movie_camera (4).png
Saving film_reel.png to film_reel (4).png
Saving film_strip_vertical.png to film_strip_vertical (4).png
Saving movie_camera.png to movie_camera (4).png
Saving public_tests.py to public_tests (4).py
Saving recsys_utils.py to recsys_utils (4).py
Saving RecSysNN.png to RecSysNN (4).png
Saving small_movie_list.csv to small_movie_list (5).csv
Saving small_movies_b.csv to small_movies_b (5).csv
Saving small_movies_R.csv to small_movies_R (5).csv
Saving small_movies_W.csv to small_movies_W (5).csv
Saving small_movies_X.csv to small_movies_X (5).csv
Saving small_movies_Y.csv to small_movies_Y (5).csv
Contenido de la carpeta 'data':
['ColabFilterL

In [62]:
import os
from google.colab import files

# Crear la carpeta 'data' si no existe
if not os.path.exists('./data'):
    os.makedirs('./data')

# Subir archivos desde tu máquina local
uploaded = files.upload()

# Mover los archivos subidos a la carpeta 'data'
for filename in uploaded.keys():
    destination = os.path.join('./data', filename)
    with open(destination, 'wb') as f:
        f.write(uploaded[filename])

# Verificar el contenido de la carpeta 'data'
print("Contenido de la carpeta 'data':")
print(os.listdir('./data'))

Saving ColabFilterLearn.PNG to ColabFilterLearn (5).PNG
Saving ColabFilterUse.PNG to ColabFilterUse (5).PNG
Saving distmatrix.PNG to distmatrix (5).PNG
Saving film_award.png to film_award (5).png
Saving film_filter.png to film_filter (5).png
Saving film_man_action.png to film_man_action (5).png
Saving film_movie_camera.png to film_movie_camera (5).png
Saving film_rating.png to film_rating (4).png
Saving film_reel.png to film_reel (5).png
Saving film_strip_vertical.png to film_strip_vertical (5).png
Saving movie_camera.png to movie_camera (5).png
Saving public_tests.py to public_tests (5).py
Saving recsys_utils.py to recsys_utils (5).py
Saving RecSysNN.png to RecSysNN (5).png
Saving small_movie_list.csv to small_movie_list (6).csv
Saving small_movies_b.csv to small_movies_b (6).csv
Saving small_movies_R.csv to small_movies_R (6).csv
Saving small_movies_W.csv to small_movies_W (6).csv
Saving small_movies_X.csv to small_movies_X (6).csv
Saving small_movies_Y.csv to small_movies_Y (6).csv


In [65]:
def load_precalc_params_small():
    file = open('small_movies_X.csv', 'r')
    X = np.loadtxt(file, delimiter=",")
    file.close()
    return X

def load_ratings_small():
    # Aquí cargarías Y y R
    Y = np.array(...)  # Código para cargar Y
    R = np.array(...)  # Código para cargar R
    return Y, R

# Llamadas a funciones para cargar datos
X = load_precalc_params_small()
Y, R = load_ratings_small()

# Imprimir formas de las matrices
print("Y", Y.shape, "R", R.shape)
print("X", X.shape)

Y () R ()
X (4778, 10)


In [67]:
def load_ratings_small():
    # Ejemplo para cargar Y y R
    Y = np.array([...])  # Asegúrate de cargar una matriz 2D
    R = np.array([...])  # Asegúrate de cargar una matriz 2D
    return Y, R

Y, R = load_ratings_small()

# Verifica la forma de Y y R
print(f"Shape of Y: {Y.shape}")
print(f"Shape of R: {R.shape}")

# Asegúrate de que Y y R tengan la forma esperada
if len(Y.shape) == 2 and len(R.shape) == 2:
    tsmean = np.mean(Y[0, R[0, :].astype(bool)])
    print(f"Average rating for movie 1: {tsmean:0.3f} / 5")
else:
    print("Y or R does not have the expected shape.")

Shape of Y: (1,)
Shape of R: (1,)
Y or R does not have the expected shape.


In [69]:
# Ejemplo con Y unidimensional
Y = np.array([4.0, 3.5, 5.0, 2.0])  # Por ejemplo, ratings para diferentes películas
R = np.array([[1, 0, 1, 1], [1, 1, 0, 1]])  # Matriz de ratings (películas x usuarios)

# Suponiendo que queremos el rating promedio de la película 1
tsmean = np.mean(Y[R[0, :].astype(bool)])
print(f"Average rating for movie 1: {tsmean:0.3f} / 5")

Average rating for movie 1: 3.667 / 5


In [70]:
# GRADED FUNCTION: cofi_cost_func
# UNQ_C1

def cofi_cost_func(X, W, b, Y, R, lambda_):
    """
    Returns the cost for the content-based filtering
    Args:
      X (ndarray (num_movies,num_features)): matrix of item features
      W (ndarray (num_users,num_features)) : matrix of user parameters
      b (ndarray (1, num_users)            : vector of user parameters
      Y (ndarray (num_movies,num_users)    : matrix of user ratings of movies
      R (ndarray (num_movies,num_users)    : matrix, where R(i, j) = 1 if the i-th movies was rated by the j-th user
      lambda_ (float): regularization parameter
    Returns:
      J (float) : Cost
    """
    nm, nu = Y.shape
    J = 0
    ### START CODE HERE ###
    for j in range(nu):
        w = W[j,:]
        b_j = b[0,j]
        for i in range(nm):
            x = X[i,:]
            y = Y[i,j]
            r = R[i,j]
            J += r * np.square((np.dot(w,x) + b_j - y ))
    J += (lambda_) * (np.sum(np.square(W)) + np.sum(np.square(X)))
    J = J/2
    ### END CODE HERE ###

    return J

In [71]:
# Public tests
from public_tests import *
test_cofi_cost_func(cofi_cost_func)

All tests passed!


In [73]:
def load_precalc_params_small():
    file_X = open('small_movies_X.csv', 'r')
    X = np.loadtxt(file_X, delimiter=",")
    file_X.close()

    # Ejemplo para cargar W y b, según corresponda
    file_W = open('small_movies_W.csv', 'r')
    W = np.loadtxt(file_W, delimiter=",")
    file_W.close()

    file_b = open('small_movies_b.csv', 'r')
    b = np.loadtxt(file_b, delimiter=",")
    file_b.close()

    return X, W, b

In [74]:
X, W, b = load_precalc_params_small()

In [76]:
print(f"Shape of b: {b.shape}")

Shape of b: (443,)


In [78]:
def load_precalc_params_small():
    file_X = open('small_movies_X.csv', 'r')
    X = np.loadtxt(file_X, delimiter=",")
    file_X.close()

    file_W = open('small_movies_W.csv', 'r')
    W = np.loadtxt(file_W, delimiter=",")
    file_W.close()

    file_b = open('small_movies_b.csv', 'r')
    b = np.loadtxt(file_b, delimiter=",")  # Suponiendo que `b` es unidimensional
    file_b.close()

    return X, W, b

In [80]:
print(f"Shape of b: {b.shape}")

Shape of b: (443,)


In [83]:
print(f"Shape of Y: {Y.shape}")

Shape of Y: (4,)


In [84]:
import numpy as np

# Función de carga de datos
def load_precalc_params_small():
    file_X = open('small_movies_X.csv', 'r')
    X = np.loadtxt(file_X, delimiter=",")
    file_X.close()

    file_W = open('small_movies_W.csv', 'r')
    W = np.loadtxt(file_W, delimiter=",")
    file_W.close()

    file_b = open('small_movies_b.csv', 'r')
    b = np.loadtxt(file_b, delimiter=",")
    file_b.close()

    return X, W, b

def load_ratings_small():
    file_Y = open('small_movies_Y.csv', 'r')
    Y = np.loadtxt(file_Y, delimiter=",")
    file_Y.close()

    file_R = open('small_movies_R.csv', 'r')
    R = np.loadtxt(file_R, delimiter=",")
    file_R.close()

    return Y, R

# Cargar datos
X, W, b = load_precalc_params_small()
Y, R = load_ratings_small()

# Reducir tamaño del conjunto de datos
num_users_r = 4
num_movies_r = 5
num_features_r = 3

X_r = X[:num_movies_r, :num_features_r]
W_r = W[:num_users_r, :num_features_r]

if b.ndim == 1:
    b_r = b[:num_users_r].reshape(1, -1)
else:
    b_r = b[0, :num_users_r].reshape(1, -1)

if Y.ndim == 1 and R.ndim == 1:
    Y_r = Y[:num_movies_r]
    R_r = R[:num_movies_r]
else:
    Y_r = Y[:num_movies_r, :num_users_r]
    R_r = R[:num_movies_r, :num_users_r]

# Evaluar la función de costo
J = cofi_cost_func(X_r, W_r, b_r, Y_r, R_r, 0)
print(f"Cost: {J:0.2f}")

Cost: 13.67


In [85]:
# Evaluate cost function with regularization
J = cofi_cost_func(X_r, W_r, b_r, Y_r, R_r, 1.5);
print(f"Cost (with regularization): {J:0.2f}")

Cost (with regularization): 28.09


In [86]:
def cofi_cost_func_v(X, W, b, Y, R, lambda_):
    """
    Returns the cost for the content-based filtering
    Vectorized for speed. Uses tensorflow operations to be compatible with custom training loop.
    Args:
      X (ndarray (num_movies,num_features)): matrix of item features
      W (ndarray (num_users,num_features)) : matrix of user parameters
      b (ndarray (1, num_users)            : vector of user parameters
      Y (ndarray (num_movies,num_users)    : matrix of user ratings of movies
      R (ndarray (num_movies,num_users)    : matrix, where R(i, j) = 1 if the i-th movies was rated by the j-th user
      lambda_ (float): regularization parameter
    Returns:
      J (float) : Cost
    """
    j = (tf.linalg.matmul(X, tf.transpose(W)) + b - Y)*R
    J = 0.5 * tf.reduce_sum(j**2) + (lambda_/2) * (tf.reduce_sum(X**2) + tf.reduce_sum(W**2))
    return J

In [87]:
# Evaluate cost function
J = cofi_cost_func_v(X_r, W_r, b_r, Y_r, R_r, 0);
print(f"Cost: {J:0.2f}")

# Evaluate cost function with regularization
J = cofi_cost_func_v(X_r, W_r, b_r, Y_r, R_r, 1.5);
print(f"Cost (with regularization): {J:0.2f}")

Cost: 13.67
Cost (with regularization): 28.09


In [89]:
import numpy as np
import pandas as pd

def load_Movie_List_pd():
    # Asegúrate de que la ruta del archivo sea correcta
    movieList_df = pd.read_csv('small_movie_list.csv')
    movieList = movieList_df.values
    return movieList, movieList_df

# Suponiendo que `num_movies` ya está definido
num_movies = 10000  # Cambia esto según el número real de películas

movieList, movieList_df = load_Movie_List_pd()

my_ratings = np.zeros(num_movies)  # Inicializa mis calificaciones

# Asegúrate de usar los IDs correctos y que existan en el dataset
my_ratings[2700] = 5
my_ratings[2609] = 2
my_ratings[929]  = 5
my_ratings[246]  = 5
my_ratings[2716] = 3
my_ratings[1150] = 5
my_ratings[382]  = 2
my_ratings[366]  = 5
my_ratings[622]  = 5
my_ratings[988]  = 3
my_ratings[2925] = 1
my_ratings[2937] = 1
my_ratings[793]  = 5

my_rated = [i for i in range(len(my_ratings)) if my_ratings[i] > 0]

print('\nNew user ratings:\n')
for i in range(len(my_ratings)):
    if my_ratings[i] > 0:
        print(f'Rated {my_ratings[i]} for  {movieList_df.loc[i,"title"]}')


New user ratings:

Rated 5.0 for  Shrek (2001)
Rated 5.0 for  Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)
Rated 2.0 for  Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)
Rated 5.0 for  Harry Potter and the Chamber of Secrets (2002)
Rated 5.0 for  Pirates of the Caribbean: The Curse of the Black Pearl (2003)
Rated 5.0 for  Lord of the Rings: The Return of the King, The (2003)
Rated 3.0 for  Eternal Sunshine of the Spotless Mind (2004)
Rated 5.0 for  Incredibles, The (2004)
Rated 2.0 for  Persuasion (2007)
Rated 5.0 for  Toy Story 3 (2010)
Rated 3.0 for  Inception (2010)
Rated 1.0 for  Louis Theroux: Law & Disorder (2008)
Rated 1.0 for  Nothing to Declare (Rien à déclarer) (2010)


In [92]:
import numpy as np

def load_ratings_small():
    # Ejemplo de carga de datos
    Y = np.loadtxt('small_movies_Y.csv', delimiter=",")
    R = np.loadtxt('small_movies_R.csv', delimiter=",")
    return Y, R

def normalizeRatings(Y, R):
    # Función de normalización de ejemplo
    Ymean = np.zeros(Y.shape[0])
    Ynorm = np.zeros(Y.shape)
    for i in range(Y.shape[0]):
        idx = R[i, :] == 1
        if np.any(idx):
            Ymean[i] = np.mean(Y[i, idx])
            Ynorm[i, idx] = Y[i, idx] - Ymean[i]
    return Ynorm, Ymean

# Cargar datos de calificaciones y ajustar tamaño
Y, R = load_ratings_small()

num_movies = Y.shape[0]  # Ajustar según el número de filas en Y
my_ratings = np.zeros(num_movies)

# Asignar calificaciones
my_ratings[2700] = 5
my_ratings[2609] = 2
# ... (otras calificaciones)

# Concatenar nuevas calificaciones con las existentes
Y = np.c_[my_ratings, Y]
R = np.c_[(my_ratings != 0).astype(int), R]

# Normalizar el dataset
Ynorm, Ymean = normalizeRatings(Y, R)

print("Normalized Ratings:", Ynorm)
print("Mean Ratings:", Ymean)

Normalized Ratings: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Mean Ratings: [3.4  3.25 2.   ... 3.5  3.5  3.5 ]


In [93]:
#  Useful Values
num_movies, num_users = Y.shape
num_features = 100

# Set Initial Parameters (W, X), use tf.Variable to track these variables
tf.random.set_seed(1234) # for consistent results
W = tf.Variable(tf.random.normal((num_users,  num_features),dtype=tf.float64),  name='W')
X = tf.Variable(tf.random.normal((num_movies, num_features),dtype=tf.float64),  name='X')
b = tf.Variable(tf.random.normal((1,          num_users),   dtype=tf.float64),  name='b')

# Instantiate an optimizer.
optimizer = keras.optimizers.Adam(learning_rate=1e-1)

In [94]:
iterations = 200
lambda_ = 1
for iter in range(iterations):
    # Use TensorFlow’s GradientTape
    # to record the operations used to compute the cost
    with tf.GradientTape() as tape:

        # Compute the cost (forward pass included in cost)
        cost_value = cofi_cost_func_v(X, W, b, Ynorm, R, lambda_)

    # Use the gradient tape to automatically retrieve
    # the gradients of the trainable variables with respect to the loss
    grads = tape.gradient( cost_value, [X,W,b] )

    # Run one step of gradient descent by updating
    # the value of the variables to minimize the loss.
    optimizer.apply_gradients( zip(grads, [X,W,b]) )

    # Log periodically.
    if iter % 20 == 0:
        print(f"Training loss at iteration {iter}: {cost_value:0.1f}")

Training loss at iteration 0: 2320849.5
Training loss at iteration 20: 136138.0
Training loss at iteration 40: 51845.0
Training loss at iteration 60: 24590.7
Training loss at iteration 80: 13626.6
Training loss at iteration 100: 8485.2
Training loss at iteration 120: 5805.7
Training loss at iteration 140: 4309.9
Training loss at iteration 160: 3433.6
Training loss at iteration 180: 2900.4


In [96]:
import numpy as np
import tensorflow as tf

# Supongamos que `p`, `Ymean`, `movieList`, `my_rated`, etc., ya están definidos
# Aquí están las formas esperadas:
# p: (4778, 444)  - Predicciones para todas las películas y usuarios
# Ymean: (4778,)  - Media de las calificaciones por película

# Asegúrate de que `Ymean` tenga la forma correcta para la operación
Ymean_expanded = np.expand_dims(Ymean, axis=1)  # Cambia la forma a (4778, 1)

# Restaurar la media
pm = p + Ymean_expanded  # Esto ahora debería funcionar

# Supongamos que `my_predictions`, `ix`, etc., ya están definidos
my_predictions = pm[:, 0]

# Ordenar predicciones
ix = tf.argsort(my_predictions, direction='DESCENDING')

for i in range(17):
    j = ix[i]
    if j not in my_rated:
        print(f'Predicting rating {my_predictions[j]:0.2f} for movie {movieList[j]}')

print('\n\nOriginal vs Predicted ratings:\n')
for i in range(len(my_ratings)):
    if my_ratings[i] > 0:
        print(f'Original {my_ratings[i]}, Predicted {my_predictions[i]:0.2f} for {movieList[i]}')

Predicting rating 4.49 for movie [4030 5.0 1 'Buzzard (2015)']
Predicting rating 4.46 for movie [1126 5.0 1 'Raise Your Voice (2004)']
Predicting rating 4.45 for movie [4271 5.0 1 'Dragons: Gift of the Night Fury (2011)']
Predicting rating 4.45 for movie [3344 5.0 1 'English Vinglish (2012)']
Predicting rating 4.45 for movie [4065 5.0 1 'Radio Day (2008)']
Predicting rating 4.45 for movie [4032 5.0 1 'Seve (2014)']
Predicting rating 4.44 for movie [560 5.0 1 'Satin Rouge (2002)']
Predicting rating 4.44 for movie [3989 5.0 1 "George Carlin: It's Bad for Ya! (2008)"]
Predicting rating 4.44 for movie [4012 5.0 1 'George Carlin: Life Is Worth Losing (2005)']
Predicting rating 4.44 for movie [2746 5.0 1 'Sisters (Syostry) (2001)']
Predicting rating 4.44 for movie [3208 5.0 1 'Front of the Class (2008)']
Predicting rating 4.44 for movie [4243 5.0 1 'Human (2015)']
Predicting rating 4.44 for movie [3623 5.0 1 'Garden of Words, The (Koto no ha no niwa) (2013)']
Predicting rating 4.44 for movie

In [97]:
filter=(movieList_df["number of ratings"] > 20)
movieList_df["pred"] = my_predictions
movieList_df = movieList_df.reindex(columns=["pred", "mean rating", "number of ratings", "title"])
movieList_df.loc[ix[:300]].loc[filter].sort_values("mean rating", ascending=False)

pred  mean rating  number of ratings               title
2700  4.677997     4.109091                 55  Toy Story 3 (2010)